Validate.isReadable should be tested on the absolute file path
If you build in Jenkins on Cloudbees, if the $HOME is defined in /private/projectodd. the following exception is thrown: 

org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: java.io.FileNotFoundException: /private/projectodd/settings-security.xml (No such file or directory)
	at org.sonatype.plexus.components.sec.dispatcher.SecUtil.read(SecUtil.java:69)
	at org.jboss.shrinkwrap.resolver.impl.maven.internal.decrypt.MavenSecurityDispatcher.<init>(MavenSecurityDispatcher.java:67)
	at org.jboss.shrinkwrap.resolver.impl.maven.internal.decrypt.MavenSettingsDecrypter.<init>(MavenSettingsDecrypter.java:47)

This change ensures that the file can be read and avoids the error while calling SecUtil.read